export SHELL="zsh"
export GOPATH="$HOME/.go"
export PATH="$GOPATH/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:/usr/local/sbin"
export KUBECONFIG="$HOME/.kube/config"
export XDG_CONFIG_HOME="$HOME/.config"
