[general]
import = ["./themes/dracula.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
duration = 0

[cursor]
blink_interval = 500
blink_timeout = 5
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 15

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[font.bold]
family = "MesloLGS Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font"

[font.glyph_offset]
x = 0
y = 0


[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[terminal.shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
startup_mode = "Windowed"

[window.dimensions]
columns = 160
lines = 50

[window.padding]
x = 4
y = 4

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u001bb"  # Alt + b - back one word

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u001bf"  # Alt + f - forward one word
